version: '3.7'
services:
  trojan-go:
    image: teddysun/trojan-go:latest
    container_name: trojan-go
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - ./trojan-go/config.json:/config.json:ro
      - ./cert:/cert:ro
    # command: [
    #   "--config", "/config.json"
    # ] 