version: '3.7'
services:
  xray:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-trojan
    restart: always
    ports:
      - "127.0.0.1:8443:8443"
    volumes:
      - ./xray/config.json:/etc/xray/config.json:ro 