version: '3.7'
services:
  trojan-go:
    image: p4gefau1t/trojan-go:latest
    container_name: trojan-go
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./trojan-go/config.json:/config.json:ro
      - ./cert:/cert:ro
    command: [
      "-config", "/config.json"
    ] 