version: '3.7'
services:
  trojan-go:
    image: trojango/trojan-go:latest
    container_name: trojan-go
    restart: always
    ports:
      - "127.0.0.1:8443:8443"
    volumes:
      - ./trojan-go/config.json:/config.json:ro
      - ./cert:/cert:ro 