version: '3.7'
services:
  trojan-go:
    image: teddysun/trojan-go:latest
    container_name: trojan-go
    restart: always
    ports:
      - "8443:8443"
    volumes:
      - /root/newbles/trojan-go/config.json:/config.json:ro
      - /root/newbles/cert:/cert:ro
    command: [ "-config", "/config.json" ] 