version: '3.7'
services:
  xray-direct:
    image: ghcr.io/xtls/xray-core:latest
    container_name: xray-direct
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./xray/config-direct.json:/etc/xray/config.json:ro
      - /root/newbles/cert:/cert:ro
    command: xray -config /etc/xray/config.json 