version: '3.7'
services:
  v2ray-direct:
    image: v2fly/v2fly-core:latest
    container_name: v2ray-direct
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./v2ray/config-direct.json:/etc/v2ray/config.json:ro
      - /root/newbles/cert:/cert:ro
    command: ["v2ray", "run", "-config", "/etc/v2ray/config.json"] 