version: '3.7'
services:
  websocket-tunnel:
    image: nginx:alpine
    container_name: ws-tunnel
    restart: always
    ports:
      - "127.0.0.1:8443:8443"
    volumes:
      - ./nginx-ws/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"] 