proxies:
  - name: "Trojan-new.bless.top"
    type: trojan
    server: new.bless.top
    port: 443
    password: "mySecureBlessPassword123"
    sni: new.bless.top
    skip-cert-verify: false

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Trojan-new.bless.top"
      - DIRECT

rules:
  - MATCH,Proxy 