proxies:
  - name: "VMess-ai.bless.top"
    type: vmess
    server: ai.bless.top
    port: 443
    uuid: 12345678-1234-5678-9abc-123456789abc
    alterId: 0
    cipher: auto
    tls: true
    skip-cert-verify: false
    servername: ai.bless.top
    network: ws
    ws-opts:
      path: /bs
      headers:
        Host: ai.bless.top

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "VMess-ai.bless.top"
      - DIRECT

rules:
  - MATCH,Proxy 