proxies:
  - name: "Trojan-ai.bless.top"
    type: trojan
    server: ai.bless.top
    port: 8443
    password: "mySecureBlessPassword123"
    sni: ai.bless.top
    skip-cert-verify: false
    network: ws
    ws-opts:
      path: /ws
      headers:
        Host: ai.bless.top

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "Trojan-ai.bless.top"
      - DIRECT

rules:
  - MATCH,Proxy 